name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
projects: ["COMP.SE.200", "software-testing"]
assignees:
  - undefined

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
      value: "Give a description of the bug!"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      value: "How to reproduce this bug?"
    validations:
      required: true

  - type: textarea
    id: user-input
    attributes:
      label: User inputs
      value: "What was inputted?"
    validations:
      required: true

  - type: textarea
    id: results
    attributes:
      label: Expected results vs. real results
      value: "What was expected?"
    validations:
      required: true

  - type: textarea
    id: seriousness
    attributes:
      label: Impact/severity
      value: "What is the criticality of the bug?"
    validations:
      required: true
    
    - type: textarea
    id: additional
    attributes:
      label: Additional information
      value: "Is there something else we should know?"
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.0 (Default)
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
